### PR TITLE
Fix phive installation in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixing #11

### CODE REVIEW

**Comment by szepeviktor** [comment]
All is very green 🍏 :)

Please decide what to do with PHP 7.1 and lower.

**Comment by szepeviktor** [comment]
Getting very close.
Please help me.

**Comment by szepeviktor** [comment]
`WP_CONTENT_DIR` magically 🔮 helped

**Comment by szepeviktor** [comment]
May I add this dependency? `"sebastian/comparator": "^2.0|^3.0|^4.0",`

PHPUnit depends on `"sebastian/comparator": "^1.2.3|^2.0|^3.0|^4.0"` causing a problem.

**Comment by szepeviktor** [comment]
17/17 green.

Please do squeeze my commits.

**Comment by leogermani** [comment]
Sorry, only now I saw all the comments! Will review it in a bit!

**Comment by szepeviktor** [comment]
Just ignore them. My internal struggle...

**Comment by szepeviktor** [comment]
@leogermani Please merge this one to check your other PR.

**Pull request merged**
