### PR TITLE
Add Local CI

### PR DESCRIPTION
**Pull request by szepeviktor**
@leogermani 

kép

Now it takes 10 seconds.

### CODE REVIEW

**Comment by leogermani** [comment]
cool, thanks!

I had to add some memory limit to phpstan with `--memory-limit` option. Do you think we should add it to the command in composer right away?

**Comment by szepeviktor** [comment]
Yes.

When CLI has `memory_limit` set is very weird!

**Comment by szepeviktor** [comment]
`php -r 'echo ini_get("memory_limit"), PHP_EOL;'`

Is your !== -1?

**Comment by leogermani** [comment]
Yes, 128M

I'm on a Mac and I don't have much experience with this OS, so don't make complcated questions. (linux user)

**Pull request merged**
